# Generated by Django 4.2.2 on 2023-06-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='modoficado',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='modoficado',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='modoficado',
            new_name='modificado',
        ),
    ]
